<?php
    return [
        'add_new' => 'Add New',
        'add_new_item' => 'Add New :Name',
        'all_items' => 'All :Name',
        'archives' => ':Name Archives',
        'attributes' => ':Name Attributes',
        'edit_item' => 'Edit :Name',
        'featured_image' => 'Featured Image',
        'filter_items_list' => 'Filter items list',
        'insert_into_item' => 'Insert into item',
        'items_list' => ':Name list',
        'items_list_navigation' => ':Name list navigation',
        'menu_name' => ':Name',
        'name' => ':Name',
        'name_admin_bar' => ':Name',
        'new_item' => 'New :Name',
        'not_found' => 'Not found',
        'not_found_in_trash' => 'Not found in Trash',
        'parent_item_colon' => 'Parent :Name:',
        'remove_featured_image' => 'Remove featured image',
        'search_items' => 'Search :Name',
        'set_featured_image' => 'Set featured image',
        'singular_name' => ':Name',
        'update_item' => 'Update :Name',
        'uploaded_to_this_item' => 'Uploaded to this item',
        'use_featured_image' => 'Use as featured image',
        'view_item' => 'View :Name',
        'view_items' => 'View :Name',

        'preview_item' => 'Preview :name',

        'item_updated' => ':Name updated.',
        'field_updated' => 'Custom field updated.',
        'field_deleted' => 'Custom field deleted.',
        'item_restored' => ':Name restored to revision from :date',
        'item_published' => ':Name published.',
        'item_saved' => ':Name saved.',
        'item_submitted' => ':Name submitted.',
        'item_scheduled' => ':Name scheduled for: <strong>:date</strong>.',
        'item_draft_updated' => ':Name draft updated.',
    ];